---
kind: pipeline
type: docker
name: hlstatsx

clone:
  depth: 1

environment: &environment
  IMAGE_VERSION: 1.0.${DRONE_BUILD_NUMBER=0}
  IMAGE_NAME: zarlo5899/hlstatsx

docker-volumes: &docker-volumes
- name: docker
  path: /var/run/docker.sock

steps:
- name: build
  image: plugin/docker
  environment: *environment
  volumes: *docker-volumes
  commands:
  - docker build -t $IMAGE_NAME:daemon -t $IMAGE_NAME:daemon-$IMAGE_VERSION ./hlstatsx-daemon

- name: publish
  image: plugin/docker
  commands:
  - docker push $IMAGE_NAME:daemon-$IMAGE_VERSION
  - docker push $IMAGE_NAME:daemon
  volumes: *docker-volumes
  environment: *environment

- name: deploy-test
  image: plugin/docker
  commands:
  - docker service update --image=$IMAGE_NAME $SERVICE_NAME
  volumes: *docker-volumes
  environment: *environment

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
